const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

// Default configuration
function getDefaultConfig() {
  return {
    apiPrefix: '/api',
    routesDir: 'src/routes',
    validatorsDir: 'src/validators',
    outputFile: 'postman.json',
    baseUrl: 'http://localhost:3000',
    collectionName: 'API Collection',
    collectionDescription: 'API collection generated by DocDoc',
    routeFilePattern: '.routes.js',
    validatorFilePattern: '.validators.js',
    authTokenName: 'token',  // Name of the Postman environment variable to store the auth token
    authTokenJsonPath: 'data.token',  // JSON path where the auth token is found in API responses
    resourceDescriptions: {},
    enableTokenCapture: true,  // Whether to add token capture scripts to auth endpoints
    zod: false  // Whether to use Zod for validation schemas
  };
}

// Load configuration
const config = loadConfig();

// Fill in missing configuration with defaults
function completeConfig(userConfig) {
  const defaultConfig = getDefaultConfig();
  const mergedConfig = { ...defaultConfig, ...userConfig };
  
  // Add default collection description if not provided
  if (!mergedConfig.collectionDescription) {
    mergedConfig.collectionDescription = `API collection for ${mergedConfig.collectionName}`;
  }

  // Set up default headers if not provided
  if (!mergedConfig.defaultHeaders) {
    mergedConfig.defaultHeaders = [
      {
        key: 'Authorization',
        value: `Bearer {{${mergedConfig.authTokenName}}}`
      },
      {
        key: 'Content-Type',
        value: 'application/json'
      }
    ];
  }

  // Set up default environment variables if not provided
  if (!mergedConfig.environmentVariables) {
    mergedConfig.environmentVariables = [
      {
        key: 'baseUrl',
        value: mergedConfig.baseUrl,
        type: 'string',
        description: 'Base URL for the API'
      },
      {
        key: mergedConfig.authTokenName,
        value: '',
        type: 'string',
        description: 'Authentication token'
      }
    ];
  }
  
  return mergedConfig;
}

// Load configuration from .docdoc file
function loadConfig() {
  try {
    const configPath = path.join(__dirname, '.docdoc');
    if (fs.existsSync(configPath)) {
      const configData = fs.readFileSync(configPath, 'utf8');
      const userConfig = JSON.parse(configData);
      return completeConfig(userConfig);
    } else {
      console.log('No .docdoc file found. Using default configuration.');
      return getDefaultConfig();
    }
  } catch (error) {
    console.error('Error loading .docdoc configuration:', error);
    console.log('Using default configuration instead.');
    return getDefaultConfig();
  }
}

// Configuration
const API_PREFIX = config.apiPrefix;
const ROUTES_DIR = path.join(__dirname, config.routesDir);
const VALIDATORS_DIR = path.join(__dirname, config.validatorsDir);
const OUTPUT_FILE = path.join(__dirname, config.outputFile);
const ROUTE_FILE_PATTERN = config.routeFilePattern;
const VALIDATOR_FILE_PATTERN = config.validatorFilePattern;

// Template for the Postman collection
const collectionTemplate = {
  info: {
    _postman_id: uuidv4(),
    name: config.collectionName,
    description: config.collectionDescription,
    schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
  },
  item: [],
  event: [
    {
      listen: 'prerequest',
      script: {
        type: 'text/javascript',
        exec: ['']
      }
    },
    {
      listen: 'test',
      script: {
        type: 'text/javascript',
        exec: ['']
      }
    }
  ],
  variable: config.environmentVariables
};

// Resource descriptions
const resourceDescriptions = config.resourceDescriptions || {};

// Add script for capturing token from auth responses
function addTokenCaptureTest() {
  if (!config.enableTokenCapture) {
    return [];
  }

  // Get token path from config or use default
  const tokenPath = config.authTokenJsonPath || 'data.token';
  const tokenPathParts = tokenPath.split('.');
  
  // Generate code to navigate the response object and find the token
  let tokenAccessCode = 'jsonData';
  for (const part of tokenPathParts) {
    tokenAccessCode += `["${part}"]`;
  }

  return [
    {
      listen: 'test',
      script: {
        type: 'text/javascript',
        exec: [
          'if (pm.response.code === 200) {',
          '    var jsonData = pm.response.json();',
          `    if (${tokenAccessCode}) {`,
          `        pm.environment.set("${config.authTokenName}", ${tokenAccessCode});`,
          '    }',
          '}'
        ]
      }
    }
  ];
}

// Generate a description for an endpoint based on method and path
function generateEndpointDescription(endpoint) {
  const { method, path, resource } = endpoint;
  
  // Generate a description based on HTTP method
  if (method === 'GET') {
    if (path.includes(':')) {
      return `Get ${resource} details`;
    } else {
      return `List ${pluralize(resource)}`;
    }
  } else if (method === 'POST') {
    return `Create ${resource}`;
  } else if (method === 'PUT') {
    return `Update ${resource}`;
  } else if (method === 'PATCH') {
    return `Partially update ${resource}`;
  } else if (method === 'DELETE') {
    return `Delete ${resource}`;
  }
  
  return `${method} ${path}`;
}

// Load validation schemas
const validationSchemas = {};

// Load validation schemas from validator files
function loadValidationSchemas() {
  try {
    if (!fs.existsSync(VALIDATORS_DIR)) {
      console.log(`Validators directory ${VALIDATORS_DIR} does not exist. Skipping validator loading.`);
      return;
    }

    const validatorFiles = fs.readdirSync(VALIDATORS_DIR)
      .filter(file => file.endsWith(VALIDATOR_FILE_PATTERN));
    
    let schemasCount = 0;
    
    validatorFiles.forEach(file => {
      try {
        const resourceName = file.replace(VALIDATOR_FILE_PATTERN, '');
        const filePath = path.join(VALIDATORS_DIR, file);
        const content = fs.readFileSync(filePath, 'utf8');
        
        // Extract schemas from content based on config
        let schemas = {};
        if (config.zod) {
          // Check if content uses Zod
          if (content.includes('const z = require(\'zod\')') || content.includes('import { z } from \'zod\'') || content.includes('import z from \'zod\'')) {
            schemas = extractZodSchemas(content, resourceName);
          } else {
            // Fallback to regular schema extraction if Zod import not found
            schemas = extractSchemas(content, resourceName);
          }
        } else {
          schemas = extractSchemas(content, resourceName);
        }
        
        Object.assign(validationSchemas, schemas);
        schemasCount += Object.keys(schemas).length;
      } catch (error) {
        console.error(`Error processing validator file ${file}:`, error);
      }
    });
    
    console.log(`Loaded ${schemasCount} validation schemas`);
  } catch (error) {
    console.error('Error loading validation schemas:', error);
  }
}

// Extract schemas from validator file content
function extractSchemas(content, resourceName) {
  const schemas = {};
  
  // Find schema definitions - match the entire schema including nested objects
  const schemaRegex = /const\s+([a-zA-Z0-9]+Schema)\s*=\s*{([^]*?)(?=\n};)/gs;
  const propertyRegex = /\s+([a-zA-Z0-9_]+):\s*{([^}]+)}/gs;
  const typeRegex = /type\s*:\s*['"]([^'"]+)['"]/i;
  const requiredRegex = /required\s*:\s*(true|false)/i;
  const minRegex = /min\s*:\s*(\d+)/i;
  const maxRegex = /max\s*:\s*(\d+)/i;
  const defaultRegex = /default\s*:\s*([^,\s]+)/i;
  const enumRegex = /enum\s*:\s*\[(.*?)\]/i;
  const itemsRegex = /items\s*:\s*{([^}]+)}/i;
  const propsRegex = /props\s*:\s*{([^}]+)}/i;
  
  let match;
  while ((match = schemaRegex.exec(content)) !== null) {
    const schemaName = match[1];
    const schemaContent = match[2];
    
    // Parse properties
    const properties = {};
    let propertyMatch;
    
    // Reset propertyRegex lastIndex to ensure we start from the beginning
    propertyRegex.lastIndex = 0;
    
    while ((propertyMatch = propertyRegex.exec(schemaContent)) !== null) {
      const propertyName = propertyMatch[1];
      const propertyContent = propertyMatch[2];
      
      // Basic property type extraction
      const typeMatch = typeRegex.exec(propertyContent);
      const requiredMatch = requiredRegex.exec(propertyContent);
      const minMatch = minRegex.exec(propertyContent);
      const maxMatch = maxRegex.exec(propertyContent);
      const defaultMatch = defaultRegex.exec(propertyContent);
      const enumMatch = enumRegex.exec(propertyContent);
      const itemsMatch = itemsRegex.exec(propertyContent);
      const propsMatch = propsRegex.exec(propertyContent);
      
      properties[propertyName] = {
        type: typeMatch ? typeMatch[1] : 'string',
        required: requiredMatch ? requiredMatch[1] === 'true' : false,
        min: minMatch ? parseInt(minMatch[1]) : undefined,
        max: maxMatch ? parseInt(maxMatch[1]) : undefined,
        default: defaultMatch ? parseDefaultValue(defaultMatch[1]) : undefined,
        enum: enumMatch ? parseEnumValues(enumMatch[1]) : undefined,
        isArray: propertyContent.includes('type: \'array\''),
        isObject: propertyContent.includes('type: \'object\''),
        hasItems: itemsMatch !== null,
        hasProps: propsMatch !== null
      };
      
      // Handle nested arrays with item definitions
      if (itemsMatch) {
        const itemTypeMatch = typeRegex.exec(itemsMatch[1]);
        properties[propertyName].itemType = itemTypeMatch ? itemTypeMatch[1] : 'string';
      }
      
      // Check if property is a nested object
      if (propertyContent.includes('props:') || propertyContent.includes('items:')) {
        properties[propertyName].isComplex = true;
      }
    }
    
    // Look for nested objects and arrays with complex item types
    const nestedObjectRegex = /\s+([a-zA-Z0-9_]+):\s*{[^}]*props\s*:\s*{([^]*?)(?=\s+}\s+})/gs;
    const nestedArrayRegex = /\s+([a-zA-Z0-9_]+):\s*{[^}]*items\s*:\s*{[^}]*type\s*:\s*['"]object['"]/gs;
    
    let nestedMatch;
    
    // Process nested objects
    while ((nestedMatch = nestedObjectRegex.exec(schemaContent)) !== null) {
      const propName = nestedMatch[1];
      if (properties[propName]) {
        properties[propName].isNestedObject = true;
        
        // Extract nested properties
        const nestedPropsRegex = /props\s*:\s*{([^]*?)(?=\s+}\s+})/s;
        const nestedPropsMatch = nestedPropsRegex.exec(nestedMatch[0]);
        
        if (nestedPropsMatch) {
          properties[propName].nestedProps = {};
          const nestedPropertyRegex = /\s+([a-zA-Z0-9_]+):\s*{([^}]+)}/gs;
          let nestedPropMatch;
          
          while ((nestedPropMatch = nestedPropertyRegex.exec(nestedPropsMatch[1])) !== null) {
            const nestedPropName = nestedPropMatch[1];
            const nestedPropContent = nestedPropMatch[2];
            
            // Extract nested property details
            const nestedTypeMatch = typeRegex.exec(nestedPropContent);
            const nestedRequiredMatch = requiredRegex.exec(nestedPropContent);
            
            properties[propName].nestedProps[nestedPropName] = {
              type: nestedTypeMatch ? nestedTypeMatch[1] : 'string',
              required: nestedRequiredMatch ? nestedRequiredMatch[1] === 'true' : false
            };
          }
        }
      }
    }
    
    // Process arrays with object items
    while ((nestedMatch = nestedArrayRegex.exec(schemaContent)) !== null) {
      const propName = nestedMatch[1];
      if (properties[propName]) {
        properties[propName].hasComplexItems = true;
        
        // Extract item properties
        const itemPropsRegex = /props\s*:\s*{([^]*?)(?=\s+}\s+})/s;
        const itemPropsMatch = itemPropsRegex.exec(nestedMatch[0]);
        
        if (itemPropsMatch) {
          properties[propName].itemProps = {};
          const itemPropertyRegex = /\s+([a-zA-Z0-9_]+):\s*{([^}]+)}/gs;
          let itemPropMatch;
          
          while ((itemPropMatch = itemPropertyRegex.exec(itemPropsMatch[1])) !== null) {
            const itemPropName = itemPropMatch[1];
            const itemPropContent = itemPropMatch[2];
            
            // Extract item property details
            const itemTypeMatch = typeRegex.exec(itemPropContent);
            const itemRequiredMatch = requiredRegex.exec(itemPropContent);
            
            properties[propName].itemProps[itemPropName] = {
              type: itemTypeMatch ? itemTypeMatch[1] : 'string',
              required: itemRequiredMatch ? itemRequiredMatch[1] === 'true' : false
            };
          }
        }
      }
    }
    
    schemas[`${resourceName}.${schemaName}`] = {
      name: schemaName,
      resource: resourceName,
      properties
    };
  }
  
  return schemas;
}

// Helper function to parse default values
function parseDefaultValue(defaultStr) {
  if (defaultStr === 'true') return true;
  if (defaultStr === 'false') return false;
  if (!isNaN(Number(defaultStr))) return Number(defaultStr);
  return defaultStr;
}

// Helper function to parse enum values
function parseEnumValues(enumStr) {
  try {
    return enumStr.split(',').map(val => {
      val = val.trim();
      // Remove quotes if present
      if ((val.startsWith('\'') && val.endsWith('\'')) || 
          (val.startsWith('"') && val.endsWith('"'))) {
        return val.substring(1, val.length - 1);
      }
      // Convert to number if numeric
      if (!isNaN(Number(val))) return Number(val);
      return val;
    });
  } catch (e) {
    return [];
  }
}

// Get endpoint name for Postman
function getEndpointName(endpoint) {
  const { method, path, resource } = endpoint;
  
  const action = {
    GET: 'Get',
    POST: 'Create',
    PUT: 'Update',
    DELETE: 'Delete',
    PATCH: 'Modify'
  }[method] || method;
  
  const resourceDisplay = endpoint.resource.charAt(0).toUpperCase() + endpoint.resource.slice(1);
  
  if (path === '/' || path === '') {
    // Listing endpoint
    return `${action} All ${pluralize(resourceDisplay)}`;
  } else if (path.includes(':')) {
    // Find the parameter in the path
    const paramMatch = path.match(/:([a-zA-Z0-9_]+)/);
    const param = paramMatch ? paramMatch[1] : 'id';
    
    // Single resource endpoint with parameter
    return `${action} ${resourceDisplay} By ${param.charAt(0).toUpperCase() + param.slice(1)}`;
  } else if (path.includes('/')) {
    // Path contains a sub-resource or action
    const parts = path.split('/').filter(p => p);
    if (parts.length > 0) {
      const lastPart = parts[parts.length - 1];
      // Convert kebab-case or snake_case to Title Case
      const formattedAction = lastPart
        .replace(/[-_]/g, ' ')
        .replace(/\w\S*/g, w => w.charAt(0).toUpperCase() + w.substr(1).toLowerCase());
      
      return `${formattedAction} ${resourceDisplay}`;
    }
  }
  
  // Default
  return `${action} ${resourceDisplay}`;
}

// Generate example request body based on endpoint details
function generateGenericExample(endpoint) {
  const { method, resource, path } = endpoint;
  const example = {};
  
  // For POST/PUT/PATCH requests
  if (method === 'POST' || method === 'PUT' || method === 'PATCH') {
    // Base examples for common resource types
    const commonFields = {
      authentication: {
        email: "user@example.com",
        password: "Password123!"
      },
      user: {
        name: "Example User",
        email: "user@example.com", 
        password: "Password123!",
        role: "USER"
      },
      profile: {
        firstName: "John",
        lastName: "Doe",
        email: "user@example.com"
      },
      organization: {
        name: "Example Organization",
        description: "Example organization description"
      },
      product: {
        name: "Example Product",
        price: 19.99,
        description: "Example description"
      },
      category: {
        name: "Example Category",
        description: "Example category description"
      },
      order: {
        customerId: "customer-id",
        items: [{ id: "item-id", quantity: 1 }]
      },
      subscription: {
        planId: "plan-id",
        startDate: new Date().toISOString().split("T")[0]
      },
      payment: {
        amount: 99.99,
        currency: "USD",
        method: "credit_card"
      },
      notification: {
        title: "Example Notification",
        message: "This is an example notification message",
        type: "INFO"
      },
      webhook: {
        url: "https://example.com/webhook",
        events: ["CREATED", "UPDATED"],
        isActive: true
      },
      setting: {
        key: "example_setting",
        value: "example_value"
      }
    };
    
    // Check if any of the common fields match our resource
    // Check for both singular and plural forms
    let finalResource = resource;
    if (resource.endsWith('s') && commonFields[resource.slice(0, -1)]) {
      finalResource = resource.slice(0, -1);
    }
    
    // Special handling for auth/authentication resources
    if (resource === 'auth') {
      finalResource = 'authentication';
    }
    
    if (commonFields[finalResource]) {
      const body = { ...commonFields[finalResource] };
      
      // For partial updates (PATCH/PUT), remove some fields
      if (method !== 'POST' && resource === 'user') {
        delete body.password;
      }
      
      // If this is a sub-path/specific action, add context-specific fields
      if (path.includes('/')) {
        const pathParts = path.split('/').filter(p => p && !p.startsWith(':'));
        const lastPart = pathParts[pathParts.length - 1];
        
        // Add token for paths that might require it
        if (lastPart.includes('reset') || lastPart.includes('verify') || 
            lastPart.includes('invite') || lastPart.includes('confirm')) {
          body.token = "verification-token";
        }
        
        // Add specific fields based on the path
        if (lastPart.includes('password')) {
          body.currentPassword = "CurrentPassword123!";
          body.newPassword = "NewPassword123!";
        }
      }
      
      return JSON.stringify(body, null, 2);
    }
    
    // Generic approach for unknown resources
    const genericExample = {
      name: `Example ${singularize(resource)}`,
      description: `Example ${singularize(resource)} description`,
    };
    
    // Add common fields based on the method
    if (method === 'POST') {
      genericExample.isActive = true;
    }
    
    return JSON.stringify(genericExample, null, 2);
  }
  
  return JSON.stringify(example, null, 2);
}

// Convert a potentially plural word to singular
function singularize(word) {
  if (word.endsWith('ies')) {
    return word.slice(0, -3) + 'y';
  } else if (word.endsWith('s') && !word.endsWith('ss')) {
    return word.slice(0, -1);
  }
  return word;
}

// Set default request body based on endpoint details
function setDefaultRequestBody(request, endpoint) {
  // Try to find a schema for this endpoint
  const schemaKey = findSchemaForEndpoint(endpoint);
  
  if (schemaKey && validationSchemas[schemaKey]) {
    const schema = validationSchemas[schemaKey];
    
    // If config.zod is true and we have parsed a Zod schema, use it to generate examples
    if (config.zod && schema.properties) {
      const exampleBody = generateExampleFromZodSchema(schema.properties);
      request.body.raw = JSON.stringify(exampleBody, null, 2);
      return;
    }
  }
  
  // Fallback to generic example if no schema found or not using Zod
  request.body.raw = generateGenericExample(endpoint);
}

// Generate example values from Zod schema properties
function generateExampleFromZodSchema(properties) {
  const example = {};
  
  Object.keys(properties).forEach(propName => {
    const prop = properties[propName];
    
    // Skip optional fields to keep the example cleaner, unless they have default values
    if (!prop.required && prop.default === undefined) {
      return;
    }
    
    // Use default value if provided
    if (prop.default !== undefined) {
      example[propName] = prop.default;
      return;
    }
    
    // Generate example values based on property type
    if (prop.isArray) {
      if (prop.type === 'string') {
        example[propName] = ['example string'];
      } else if (prop.type === 'number' || prop.type === 'integer') {
        example[propName] = [prop.min !== undefined ? prop.min : 1];
      } else if (prop.type === 'boolean') {
        example[propName] = [true];
      } else if (prop.type === 'date') {
        example[propName] = [new Date().toISOString().split('T')[0]];
      } else if (prop.type === 'object' || prop.hasComplexItems) {
        // Handle array of objects
        const itemExample = {};
        if (prop.itemProps) {
          Object.keys(prop.itemProps).forEach(itemPropName => {
            const itemProp = prop.itemProps[itemPropName];
            if (itemProp.required || itemProp.default !== undefined) {
              itemExample[itemPropName] = getExampleValueForType(itemProp.type, itemProp.min, itemProp.max, itemProp.default);
            }
          });
        } else {
          // Generic object if we don't have item properties
          itemExample.id = 1;
          itemExample.name = "Example Item";
        }
        example[propName] = [itemExample];
      } else if (prop.type === 'enum' && prop.enum && prop.enum.length > 0) {
        // Array of enum values - use the first enum value
        example[propName] = [prop.enum[0]];
      } else {
        // Generic array for other types
        example[propName] = ["example item"];
      }
    } else if (prop.type === 'object' && prop.nestedProps) {
      // Handle nested objects
      const nestedExample = {};
      Object.keys(prop.nestedProps).forEach(nestedPropName => {
        const nestedProp = prop.nestedProps[nestedPropName];
        if (nestedProp.required || nestedProp.default !== undefined) {
          nestedExample[nestedPropName] = getExampleValueForType(
            nestedProp.type, 
            nestedProp.min, 
            nestedProp.max,
            nestedProp.default
          );
        }
      });
      example[propName] = nestedExample;
    } else if (prop.type === 'object' && prop.isObject) {
      // Generic object if we don't have specific nested properties
      example[propName] = {
        id: 1,
        name: "Example Object"
      };
    } else if (prop.type === 'enum' && prop.enum && prop.enum.length > 0) {
      // Use first enum value as example
      example[propName] = prop.enum[0];
    } else if (prop.isNullable) {
      // For nullable fields without a default, use null as example
      example[propName] = null;
    } else {
      // Use basic types
      example[propName] = getExampleValueForType(prop.type, prop.min, prop.max);
    }
  });
  
  return example;
}

// Get example value for a given type with more accurate examples
function getExampleValueForType(type, min, max, defaultValue) {
  // If default is provided, use it
  if (defaultValue !== undefined) {
    return defaultValue;
  }
  
  switch (type) {
    case 'string':
      return min ? 'a'.repeat(min) : 'example';
    case 'email':
      return 'user@example.com';
    case 'url':
      return 'https://example.com';
    case 'uuid':
      return '123e4567-e89b-12d3-a456-426614174000';
    case 'number':
      return min !== undefined ? min : max !== undefined ? Math.min(max, 10) : 1;
    case 'integer':
      return min !== undefined ? Math.ceil(min) : max !== undefined ? Math.min(Math.floor(max), 10) : 1;
    case 'boolean':
      return true;
    case 'date':
      return new Date().toISOString().split('T')[0];
    case 'datetime':
      return new Date().toISOString();
    case 'time':
      return new Date().toISOString().split('T')[1].split('.')[0];
    case 'record':
      return { key1: 'value1', key2: 'value2' };
    case 'literal':
      return 'literal value';
    case 'union':
      return 'example union';
    default:
      return 'example';
  }
}

// Get route files content
function getRouteFiles() {
  try {
    if (!fs.existsSync(ROUTES_DIR)) {
      console.error(`Routes directory ${ROUTES_DIR} does not exist.`);
      return [];
    }

    return fs.readdirSync(ROUTES_DIR)
      .filter(file => file.endsWith(ROUTE_FILE_PATTERN))
      .map(file => ({
        path: path.join(ROUTES_DIR, file),
        resource: file.replace(ROUTE_FILE_PATTERN, '')
      }));
  } catch (error) {
    console.error('Error reading routes directory:', error);
    return [];
  }
}

// Get route file content
function getRouteContent(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (error) {
    console.error(`Error reading file ${filePath}:`, error);
    return '';
  }
}

// Process route files to extract routes
function processRouteFiles() {
  if (!fs.existsSync(ROUTES_DIR)) {
    console.error(`Routes directory ${ROUTES_DIR} does not exist.`);
    return [];
  }

  const routes = [];
  const routeFiles = fs.readdirSync(ROUTES_DIR)
    .filter(file => file.endsWith(ROUTE_FILE_PATTERN));

  routeFiles.forEach(file => {
    const resourceName = file.replace(ROUTE_FILE_PATTERN, '');
    const filePath = path.join(ROUTES_DIR, file);
    const content = getRouteContent(filePath);
    
    const extractedRoutes = extractRoutesFromContent(content, resourceName);
    routes.push(...extractedRoutes);
  });

  return routes;
}

// Extract routes from file content
function extractRoutesFromContent(content, resourceName) {
  const routeMethods = ['get', 'post', 'put', 'patch', 'delete'];
  const routes = [];
  
  // Match for router.method('path', ...)
  const routeRegex = new RegExp(`router\\.(${routeMethods.join('|')})\\(['"](.*?)['"]`, 'g');
  
  let match;
  while ((match = routeRegex.exec(content)) !== null) {
    const method = match[1].toUpperCase();
    const path = match[2].startsWith('/') ? match[2] : `/${match[2]}`;
    
    // Properly construct the full path with the resource name
    const fullPath = `/${resourceName}${path}`;
    
    routes.push({
      method,
      path: fullPath,
      resource: resourceName,
      fullPath: API_PREFIX + fullPath
    });
  }
  
  return routes;
}

// Find route files
function getRouteFiles() {
  try {
    return fs.readdirSync(ROUTES_DIR)
      .filter(file => file.endsWith('.routes.js'))
      .map(file => ({
        path: path.join(ROUTES_DIR, file),
        resource: file.replace('.routes.js', '')
      }));
  } catch (error) {
    console.error('Error reading routes directory:', error);
    return [];
  }
}

// Parse route file to extract endpoints
function parseRouteFile(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const resourceName = path.basename(filePath, '.routes.js');
    const lines = content.split('\n');
    const endpoints = [];

    // Regular expressions to match router method definitions
    const routerMethodRegex = /router\.(get|post|put|delete|patch)\(['"]([^'"]+)['"]/i;
    const routeCommentRegex = /\s*\/\*\*\s*\n\s*\*\s*@route\s+(GET|POST|PUT|DELETE|PATCH)\s+([^\n]+)\s*\n\s*\*\s*@desc\s+([^\n]+)/i;
    const middlewareRegex = /validate\(\s*([a-zA-Z0-9]+Schema)\s*\)/;

    let currentComment = null;
    let schemaName = null;

    for (let i = 0; i < lines.length; i++) {
      // Check for route comments
      const commentMatch = routeCommentRegex.exec(lines[i]);
      if (commentMatch) {
        currentComment = {
          method: commentMatch[1],
          path: commentMatch[2].trim(),
          description: commentMatch[3].trim()
        };
        continue;
      }

      // Check for router method definitions
      const methodMatch = routerMethodRegex.exec(lines[i]);
      if (methodMatch) {
        const method = methodMatch[1].toUpperCase();
        const path = methodMatch[2];
        
        // Get validation schema if present
        const validationMatch = middlewareRegex.exec(lines[i]);
        schemaName = validationMatch ? validationMatch[1] : null;
        
        // Use the comment if available, otherwise create default
        const endpoint = {
          method,
          path: path.startsWith('/') ? path : `/${path}`,
          fullPath: `/api/${resourceName}${path.startsWith('/') ? path : `/${path}`}`,
          description: currentComment ? currentComment.description : `${method} endpoint for ${resourceName}`,
          resource: resourceName,
          schemaName
        };
        
        endpoints.push(endpoint);
        currentComment = null;
        schemaName = null;
      }
    }

    return endpoints;
  } catch (error) {
    console.error(`Error parsing route file ${filePath}: ${error.message}`);
    return [];
  }
}

// Find schema name that matches the endpoint
function findSchemaForEndpoint(endpoint) {
  // Common schema name patterns
  const schemaPatterns = [
    // POST patterns
    { method: 'POST', pathPattern: /^\/?$/, schemaPattern: 'create([A-Z][a-z]+)Schema' },
    { method: 'POST', pathPattern: /^\/?$/, schemaPattern: 'add([A-Z][a-z]+)Schema' },
    
    // PUT patterns
    { method: 'PUT', pathPattern: /\/:id$/, schemaPattern: 'update([A-Z][a-z]+)Schema' },
    { method: 'PUT', pathPattern: /\/:id$/, schemaPattern: 'edit([A-Z][a-z]+)Schema' },
    
    // PATCH patterns
    { method: 'PATCH', pathPattern: /\/:id\/([a-z-]+)$/, schemaPattern: 'toggle([A-Z][a-z]+)Schema' },
    { method: 'PATCH', pathPattern: /\/:id\/([a-z-]+)$/, schemaPattern: 'update([A-Z][a-z]+)([A-Z][a-z]+)Schema' },
    
    // Specific patterns for auth
    { method: 'POST', path: '/signin', schemaKey: 'auth.signinSchema' },
    { method: 'POST', path: '/signup', schemaKey: 'auth.signupSchema' },
    { method: 'POST', path: '/signup-with-invite', schemaKey: 'auth.signupWithInviteSchema' },
    { method: 'POST', path: '/reset-password', schemaKey: 'auth.resetPasswordSchema' },
    { method: 'POST', path: '/forgot-password', schemaKey: 'auth.forgotPasswordSchema' },
  ];
  
  // Check for exact path matches first
  const exactMatch = schemaPatterns.find(pattern => 
    pattern.path && pattern.method === endpoint.method && pattern.path === endpoint.path
  );
  
  if (exactMatch && exactMatch.schemaKey) {
    return exactMatch.schemaKey;
  }
  
  // Look for a schema that matches the endpoint's resource and method
  const resourceSchemas = Object.keys(validationSchemas)
    .filter(key => key.startsWith(`${endpoint.resource}.`));
  
  // Match by schema name and path pattern
  for (const pattern of schemaPatterns) {
    if (pattern.method === endpoint.method && 
        pattern.pathPattern && 
        pattern.pathPattern.test(endpoint.path)) {
      for (const schemaKey of resourceSchemas) {
        const schemaName = validationSchemas[schemaKey].name;
        const regexPattern = new RegExp(pattern.schemaPattern.replace(/\([^)]+\)/g, '.*'));
        
        if (regexPattern.test(schemaName)) {
          return schemaKey;
        }
      }
    }
  }
  
  // Try to match by combining resource and endpoint name
  let endpointAction = '';
  if (endpoint.method === 'POST') {
    endpointAction = 'create';
  } else if (endpoint.method === 'PUT') {
    endpointAction = 'update';
  } else if (endpoint.method === 'PATCH') {
    endpointAction = 'update';
    // Extract the action from path for PATCH endpoints like /resource/:id/action
    const actionMatch = endpoint.path.match(/\/([a-z-]+)$/);
    if (actionMatch) {
      endpointAction = actionMatch[1].replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    }
  }
  
  if (endpointAction) {
    // Try various schema naming patterns
    const schemaPatterns = [
      `${endpoint.resource}.${endpointAction}Schema`,
      `${endpoint.resource}.${endpointAction}${capitalizeFirstLetter(endpoint.resource)}Schema`,
      `${endpoint.resource}.${endpoint.resource}${capitalizeFirstLetter(endpointAction)}Schema`,
    ];
    
    for (const schemaKey of schemaPatterns) {
      if (validationSchemas[schemaKey]) {
        return schemaKey;
      }
    }
  }
  
  // Fallback: try to find any schema for this resource that might be relevant
  for (const schemaKey of resourceSchemas) {
    const schemaName = validationSchemas[schemaKey].name;
    // POST endpoints often use create/add schemas
    if (endpoint.method === 'POST' && (
      schemaName.includes('create') || 
      schemaName.includes('add') || 
      schemaName.includes('new')
    )) {
      return schemaKey;
    }
    // PUT/PATCH endpoints often use update/edit schemas
    if ((endpoint.method === 'PUT' || endpoint.method === 'PATCH') && (
      schemaName.includes('update') || 
      schemaName.includes('edit') ||
      schemaName.includes('modify')
    )) {
      return schemaKey;
    }
  }
  
  return null;
}

function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

// Map Express routes to Postman items
function mapRoutesToPostmanItems(routes) {
  return routes.map(route => {
    const endpoint = extractEndpointDetails(route);
    
    // Find appropriate schema for this endpoint
    const schemaKey = findSchemaForEndpoint(endpoint);
    
    // Create request item
    const item = {
      name: getEndpointName(endpoint),
      request: createPostmanRequest(endpoint, schemaKey),
      response: []
    };
    
    // Add auth token capture for signin endpoints
    if (endpoint.resource === 'auth' && endpoint.path.includes('signin') && config.enableTokenCapture) {
      item.event = addTokenCaptureTest();
    }
    
    return item;
  });
}

// Create Postman request object
function createPostmanRequest(endpoint, schemaKey) {
  // Create the request object
  const request = {
    method: endpoint.method,
    header: [
      {
        key: 'Content-Type',
        value: 'application/json'
      }
    ],
    url: {
      raw: `{{baseUrl}}${endpoint.fullPath}`,
      host: [
        '{{baseUrl}}'
      ],
      path: endpoint.fullPath.split('/').filter(segment => segment !== '')
    },
    description: endpoint.description || `${endpoint.method} ${endpoint.path}`
  };
  
  // Add authorization header for protected endpoints
  // Skip auth header for authentication endpoints
  const isAuthEndpoint = endpoint.resource === 'auth' || endpoint.resource === 'authentication';
  const isPublicEndpoint = isAuthEndpoint && (
    endpoint.path.includes('/') && (
      endpoint.path.toLowerCase().includes('signup') || 
      endpoint.path.toLowerCase().includes('signin') || 
      endpoint.path.toLowerCase().includes('login') ||
      endpoint.path.toLowerCase().includes('register') ||
      endpoint.path.toLowerCase().includes('forgot') ||
      endpoint.path.toLowerCase().includes('reset')
    )
  );
  
  if (!isPublicEndpoint) {
    request.header.push({
      key: 'Authorization',
      value: `Bearer {{${config.authTokenName}}}`,
      type: 'text'
    });
  }
  
  // Extract URL parameters
  const pathParams = [];
  const pathParamRegex = /:([a-zA-Z0-9_]+)/g;
  let paramMatch;
  
  while ((paramMatch = pathParamRegex.exec(endpoint.path)) !== null) {
    pathParams.push(paramMatch[1]);
  }
  
  // Add path parameters
  if (pathParams.length > 0) {
    request.url.variable = pathParams.map(param => ({
      key: param,
      value: param === 'id' ? '123e4567-e89b-12d3-a456-426614174000' : `{{${param}}}`,
      description: `The ${param} parameter`
    }));
  }
  
  // Set request body for methods that accept body
  if (['POST', 'PUT', 'PATCH'].includes(endpoint.method)) {
    request.body = {
      mode: 'raw',
      raw: '{}',
      options: {
        raw: {
          language: 'json'
        }
      }
    };
    
    // Generate example request body
    setDefaultRequestBody(request, endpoint);
  }
  
  return request;
}

// Simple pluralize function
function pluralize(word) {
  if (word.endsWith('s')) {
    return word;
  }
  if (word.endsWith('y')) {
    return word.slice(0, -1) + 'ies';
  }
  return word + 's';
}

// Main function to parse routes and generate collection
function generateCollection() {
  try {
    // Get all route files
    const routes = processRouteFiles();
    
    // Create the collection structure
    const collection = JSON.parse(JSON.stringify(collectionTemplate));
    
    // Group endpoints by resource
    const folders = {};
    
    routes.forEach(route => {
      const endpoint = extractEndpointDetails(route);
      const resourceName = endpoint.resource;
      
      if (!folders[resourceName]) {
        folders[resourceName] = {
          name: resourceName.charAt(0).toUpperCase() + resourceName.slice(1),
          description: resourceDescriptions[resourceName] || `${resourceName} endpoints`,
          item: []
        };
      }
      
      // Find schema for this endpoint
      const schemaKey = findSchemaForEndpoint(endpoint);
      
      // Create request item
      const item = {
        name: getEndpointName(endpoint),
        request: createPostmanRequest(endpoint, schemaKey),
        response: []
      };
      
      // Add auth token capture for authentication endpoints with POST method
      if ((resourceName === 'auth' || resourceName === 'authentication') && 
          endpoint.method === 'POST' && config.enableTokenCapture) {
        item.event = addTokenCaptureTest();
      }
      
      folders[resourceName].item.push(item);
    });
    
    // Add folders to collection
    collection.item = Object.values(folders).sort((a, b) => a.name.localeCompare(b.name));
    
    return collection;
  } catch (error) {
    console.error('Error generating collection:', error);
    throw error;
  }
}

// Main function
function main() {
  try {
    // Check if directories exist and create them if necessary
    ensureDirectoriesExist();
    
    // Load validation schemas first
    loadValidationSchemas();
    
    // Generate collection
    const collection = generateCollection();
    
    // Create output directory if it doesn't exist
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write collection to file
    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(collection, null, 2));
    
    console.log(`Postman collection generated successfully at ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('Error generating Postman collection:', error);
    process.exit(1);
  }
}

// Ensure required directories exist
function ensureDirectoriesExist() {
  // Check if routes directory exists
  if (!fs.existsSync(ROUTES_DIR)) {
    console.warn(`Routes directory ${ROUTES_DIR} does not exist. Creating it...`);
    fs.mkdirSync(ROUTES_DIR, { recursive: true });
  }

  // Check if validators directory exists
  if (!fs.existsSync(VALIDATORS_DIR)) {
    console.warn(`Validators directory ${VALIDATORS_DIR} does not exist. Creating it...`);
    fs.mkdirSync(VALIDATORS_DIR, { recursive: true });
  }
}

// Run the main function
main();

// Extract endpoint details from route info
function extractEndpointDetails(route) {
  const { path, method, resource, fullPath } = route;
  
  // Generate a more useful description using the dynamic generator
  const description = generateEndpointDescription({ path, method, resource });
  
  // Use the provided fullPath if available, otherwise construct it
  const endpointFullPath = fullPath || (API_PREFIX + path);
  
  return {
    path,
    method,
    resource,
    description,
    fullPath: endpointFullPath
  };
}

// Organize endpoints into folders by resource
function organizeEndpoints(routes) {
  const folders = {};
  
  // Map routes to Postman items
  const items = mapRoutesToPostmanItems(routes);
  
  // Group items by resource
  items.forEach(item => {
    const endpoint = extractEndpointDetails(routes.find(
      route => route.path === item.request.url.path.replace(API_PREFIX, '') && 
               route.method === item.request.method
    ));
    
    const resourceName = endpoint.resource;
    
    if (!folders[resourceName]) {
      folders[resourceName] = {
        name: capitalizeFirstLetter(resourceName),
        item: []
      };
    }
    
    folders[resourceName].item.push(item);
  });
  
  // Sort folders by name
  return Object.values(folders).sort((a, b) => a.name.localeCompare(b.name));
}

// Extract Zod schemas from validator file content
function extractZodSchemas(content, resourceName) {
  const schemas = {};
  
  try {
    // Find Zod schema definitions with improved regex
    const schemaRegex = /const\s+([a-zA-Z0-9]+Schema)\s*=\s*z\.(object|string|number|boolean|array|date)\(\)([^]*?)(?=;\s*($|\/\/|\/\*|export|const|let|var))/gs;
    
    let match;
    while ((match = schemaRegex.exec(content)) !== null) {
      const schemaName = match[1];
      const schemaType = match[2]; // object, string, number, etc.
      const schemaContent = match[3];
      
      // Parse properties for object type schemas
      const properties = {};
      
      if (schemaType === 'object') {
        // Look for shape pattern
        const shapeRegex = /\.shape\(\s*{([^]*?)}\s*\)/s;
        const shapeMatch = shapeRegex.exec(schemaContent);
        
        if (shapeMatch) {
          // Get field definitions
          const fieldsContent = shapeMatch[1];
          
          // Match field patterns, handling multi-line definitions
          const fieldPattern = /\s*([a-zA-Z0-9_]+)\s*:\s*z\.([^,]*?),?(?=\s*\w+\s*:|$)/gs;
          let fieldMatch;
          
          while ((fieldMatch = fieldPattern.exec(fieldsContent)) !== null) {
            try {
              const fieldName = fieldMatch[1];
              const fieldDef = fieldMatch[2];
              
              // Skip empty matches
              if (!fieldName || !fieldDef) continue;
              
              // Parse field type and constraints
              parseZodField(properties, fieldName, fieldDef);
            } catch (fieldError) {
              console.warn(`Error parsing field in schema ${schemaName}: ${fieldError.message}`);
            }
          }
        }
      }
      
      schemas[`${resourceName}.${schemaName}`] = {
        name: schemaName,
        resource: resourceName,
        properties
      };
    }
  } catch (error) {
    console.error(`Error extracting Zod schemas from ${resourceName}: ${error.message}`);
  }
  
  return schemas;
}

// Parse a single Zod field definition
function parseZodField(properties, fieldName, fieldDef) {
  // Initialize defaults
  let fieldType = 'string';
  let isRequired = true;
  let isArray = false;
  let isObject = false;
  let min, max, defaultValue, enumValues;
  
  // Detect array types
  if (fieldDef.includes('array()')) {
    isArray = true;
    fieldType = 'array';
    
    // Determine array item type
    const ofTypeMatch = /\.of\(z\.(\w+)/.exec(fieldDef);
    if (ofTypeMatch) {
      let itemType = ofTypeMatch[1];
      
      // Handle array of objects with nested properties
      if (itemType === 'object' && fieldDef.includes('shape(')) {
        itemType = 'object';
        // Future enhancement: parse nested object fields
      }
      
      fieldType = itemType;
    }
  }
  // Detect object types with shape
  else if (fieldDef.includes('object()') && fieldDef.includes('shape(')) {
    isObject = true;
    fieldType = 'object';
    // Future enhancement: parse nested object fields
  }
  // Handle string type with validations
  else if (fieldDef.startsWith('string')) {
    fieldType = 'string';
    
    // Extract common string validations
    if (fieldDef.includes('.email()')) fieldType = 'email';
    if (fieldDef.includes('.url()')) fieldType = 'url';
    if (fieldDef.includes('.uuid()')) fieldType = 'uuid';
    
    // Get string constraints
    min = extractNumber(fieldDef, /\.min\((\d+)\)/);
    max = extractNumber(fieldDef, /\.max\((\d+)\)/);
    defaultValue = extractDefault(fieldDef, /\.default\(['"]([^'"]*)['"]\)/);
  }
  // Handle number type with validations
  else if (fieldDef.startsWith('number')) {
    fieldType = 'number';
    
    // Extract number validations
    if (fieldDef.includes('.int()')) fieldType = 'integer';
    
    // Get number constraints
    min = extractNumber(fieldDef, /\.min\((\d+(?:\.\d+)?)\)/);
    max = extractNumber(fieldDef, /\.max\((\d+(?:\.\d+)?)\)/);
    defaultValue = extractNumber(fieldDef, /\.default\((\d+(?:\.\d+)?)\)/);
  }
  // Handle boolean type
  else if (fieldDef.startsWith('boolean')) {
    fieldType = 'boolean';
    defaultValue = fieldDef.includes('.default(true)') ? true : 
                  fieldDef.includes('.default(false)') ? false : undefined;
  }
  // Handle date type
  else if (fieldDef.startsWith('date')) {
    fieldType = 'date';
  }
  // Handle enum types
  else if (fieldDef.includes('enum(') || fieldDef.includes('nativeEnum(')) {
    fieldType = 'enum';
    // Try to extract enum values from different formats
    try {
      // Extract from array format [...]
      const enumMatch = /\[(.*?)\]/.exec(fieldDef);
      if (enumMatch) {
        enumValues = parseZodEnumValues(enumMatch[1]);
      }
    } catch (e) {
      console.warn(`Error parsing enum values: ${e.message}`);
    }
  }
  
  // Check for optional and nullable modifiers
  isRequired = !fieldDef.includes('.optional()');
  const isNullable = fieldDef.includes('.nullable()');
  
  // Store parsed field data
  properties[fieldName] = {
    type: fieldType,
    required: isRequired,
    isNullable,
    min,
    max,
    default: defaultValue,
    enum: enumValues,
    isArray,
    isObject
  };
}

// Helper to extract numeric values from patterns
function extractNumber(str, pattern) {
  const match = pattern.exec(str);
  return match ? parseFloat(match[1]) : undefined;
}

// Helper to extract default values
function extractDefault(str, pattern) {
  const match = pattern.exec(str);
  return match ? match[1] : undefined;
}

// Helper function to parse Zod enum values
function parseZodEnumValues(enumStr) {
  try {
    return enumStr.split(',').map(val => {
      val = val.trim();
      // Remove quotes if present
      if ((val.startsWith('\'') && val.endsWith('\'')) || 
          (val.startsWith('"') && val.endsWith('"'))) {
        return val.substring(1, val.length - 1);
      }
      // Convert to number if numeric
      if (!isNaN(Number(val))) return Number(val);
      return val;
    });
  } catch (e) {
    return [];
  }
} 